/**
 * Sprint 89 — the PAPER dry-run folder landing overview.
 *
 * `fixtures/dry-run-sample/` is a REAL, committed `paper:sniper:dry-run` output (generated by the
 * production orchestrator over the fictional dress-rehearsal example; apps/cli's
 * dress-rehearsal-examples.test.ts byte-pins it against a fresh run, so it can never drift).
 * These tests prove the overview is read verbatim from the operator bundle, degrades to `null`
 * for ordinary folders, never throws on hostile shapes, and renders a safe, deterministic,
 * SIMULATION-ONLY landing block.
 */

import { readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { buildFolderIndex, type FolderInputEntry } from "../src/lib/folder-index.js";
import {
  buildDryRunOverview,
  routeStatusExplanation,
  DRY_RUN_BUNDLE_SCHEMA,
} from "../src/lib/dry-run-overview.js";
import { hasTypedView } from "../src/components/artifact-views.js";
import { renderToString } from "../src/lib/html.js";
import { renderFolderIndex } from "../src/pages/folder.js";

const OPTS = { hasTypedView } as const;

const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), "../fixtures");

/** Read a fixture folder into scan entries the same way the inspector classifies them. */
function loadFolder(dir: string): FolderInputEntry[] {
  return readdirSync(dir).map((name) => {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) return { name, type: "skipped", reason: "subdirectory" };
    if (!name.toLowerCase().endsWith(".json")) return { name, type: "skipped", reason: "not a .json file" };
    return { name, type: "json", text: readFileSync(full, "utf8") };
  });
}

const dryRunIndex = () => buildFolderIndex(loadFolder(join(FIXTURES, "dry-run-sample")), OPTS);

describe("buildDryRunOverview — detection", () => {
  it("returns null for an ordinary artifact folder (no operator bundle)", () => {
    const index = buildFolderIndex(loadFolder(join(FIXTURES, "folder-sample")), OPTS);
    expect(buildDryRunOverview(index)).toBeNull();
  });

  it("returns null for an empty folder", () => {
    expect(buildDryRunOverview(buildFolderIndex([], OPTS))).toBeNull();
  });

  it("ignores a MALFORMED file even if named like a bundle", () => {
    const index = buildFolderIndex([{ name: "operator-bundle.json", type: "json", text: "{nope" }], OPTS);
    expect(buildDryRunOverview(index)).toBeNull();
  });
});

describe("buildDryRunOverview — the real committed dry-run output", () => {
  it("reads the verdict, route, codes, and counts verbatim from the bundle", () => {
    const overview = buildDryRunOverview(dryRunIndex());
    expect(overview).not.toBeNull();
    expect(overview!.bundleName).toBe("operator-bundle.json");
    expect(overview!.operatorVerdict).toBe("blocked");
    expect(overview!.bundleLabel).toBe("rehearsal-rich");
    expect(overview!.operatorLabel).toBe("rehearsal-operator");
    expect(overview!.complete).toBe(true);
    expect(overview!.blockingTrailConsistent).toBe(true);
    expect(overview!.routeResolutionStatus).toBe("unavailable");
    expect(overview!.routeResolverAttempted).toBe(false);
    expect(overview!.simulationReadyPerReadiness).toBe(true);
    expect(overview!.chainBlockingCodes.items).toEqual(["simulation-blocked-prereqs-not-ready"]);
    expect(overview!.whatHappened).toContain("13/13 artifacts strictly valid");
    expect(overview!.whatToInspectNext.items.length).toBeGreaterThan(0);
    expect(overview!.hasRunSummary).toBe(true);
  });

  it("maps all 13 chain roles to valid, file-backed, anchored states", () => {
    const overview = buildDryRunOverview(dryRunIndex())!;
    expect(overview.roles).toHaveLength(13);
    expect(overview.rolesHidden).toBe(0);
    expect(overview.validRoleCount).toBe(13);
    expect(overview.invalidRoleCount).toBe(0);
    expect(overview.missingRoleCount).toBe(0);
    for (const role of overview.roles) {
      expect(role.state, role.role).toBe("valid");
      expect(role.fileName, role.role).not.toBeNull();
      expect(role.digest, role.role).toMatch(/^sha256-128:[0-9a-f]{32}$/);
      expect(role.anchor, role.role).not.toBeNull();
    }
  });

  it("is deterministic: the same folder produces a deeply equal overview", () => {
    expect(JSON.stringify(buildDryRunOverview(dryRunIndex()))).toBe(
      JSON.stringify(buildDryRunOverview(dryRunIndex())),
    );
  });
});

describe("buildDryRunOverview — hostile / degraded bundle shapes (never throws, never invents)", () => {
  function indexFor(bundle: unknown) {
    return buildFolderIndex([{ name: "operator-bundle.json", type: "json", text: JSON.stringify(bundle) }], OPTS);
  }

  it("a bundle with every field wrong-typed yields nulls and empty lists", () => {
    const overview = buildDryRunOverview(
      indexFor({
        schemaVersion: DRY_RUN_BUNDLE_SCHEMA,
        operatorVerdict: 42,
        complete: "yes",
        blockingTrailConsistent: 1,
        routeResolutionStatus: [],
        chainBlockingCodes: "nope",
        whyBlocked: { a: 1 },
        whatHappened: false,
        whatToInspectNext: null,
        artifacts: "not-an-array",
        files: 7,
      }),
    );
    expect(overview).not.toBeNull();
    expect(overview!.operatorVerdict).toBeNull();
    expect(overview!.complete).toBeNull();
    expect(overview!.blockingTrailConsistent).toBeNull();
    expect(overview!.routeResolutionStatus).toBeNull();
    expect(overview!.chainBlockingCodes.items).toEqual([]);
    expect(overview!.whyBlocked.items).toEqual([]);
    expect(overview!.whatHappened).toBeNull();
    expect(overview!.roles).toEqual([]);
    expect(overview!.hasRunSummary).toBe(false);
  });

  it("a role with present:false is 'missing'; present without valid is 'invalid'", () => {
    const overview = buildDryRunOverview(
      indexFor({
        schemaVersion: DRY_RUN_BUNDLE_SCHEMA,
        artifacts: [
          { role: "decisions", present: false, valid: false },
          { role: "intent-plan", present: true, valid: false },
          { role: "readiness", present: true, valid: true },
          { notRoleShaped: true },
          "garbage",
        ],
        files: [{ role: "readiness", fileName: "readiness.json", digest: "sha256-128:00000000000000000000000000000000" }],
      }),
    )!;
    expect(overview.roles.map((r) => [r.role, r.state])).toEqual([
      ["decisions", "missing"],
      ["intent-plan", "invalid"],
      ["readiness", "valid"],
    ]);
    // The file-less roles carry no fileName/digest/anchor — nothing invented.
    expect(overview.roles[0]!.fileName).toBeNull();
    expect(overview.roles[1]!.digest).toBeNull();
    expect(overview.missingRoleCount).toBe(1);
    expect(overview.invalidRoleCount).toBe(1);
  });
});

describe("routeStatusExplanation — honest per-status wording", () => {
  it("explains each known status and never invents one for unknowns", () => {
    expect(routeStatusExplanation("unavailable")).toContain("nothing was faked");
    expect(routeStatusExplanation("blocked")).toContain("no resolution was attempted");
    expect(routeStatusExplanation("no_entries")).toContain("nothing to resolve");
    expect(routeStatusExplanation("resolved")).toContain("PAPER only");
    expect(routeStatusExplanation(null)).toContain("nothing was invented");
    expect(routeStatusExplanation("???")).toContain("nothing was invented");
  });
});

describe("renderFolderIndex — dry-run landing block", () => {
  const FORBIDDEN: readonly RegExp[] = [
    /<script/i,
    /\bfetch\s*\(/,
    /\bXMLHttpRequest\b/,
    /ready to trade/i,
    /live[- ]ready/i,
    /\[object Object\]/,
    /\bundefined\b/,
  ];

  it("renders the PAPER-only banner, verdict card, chain, and blocking codes for the real output", () => {
    const page = renderToString(renderFolderIndex(dryRunIndex(), { name: "dry-run-sample" }));
    expect(page).toContain("PAPER dry-run output — SIMULATION ONLY");
    expect(page).toContain("Dry-run result");
    expect(page).toContain("Operator verdict");
    expect(page).toContain("blocked");
    expect(page).toContain("Artifact chain");
    expect(page).toContain("sm-chainrole");
    expect(page).toContain("simulation-blocked-prereqs-not-ready");
    expect(page).toContain("RUN_SUMMARY.md");
    expect(page).toContain("nothing was faked");
    for (const pattern of FORBIDDEN) {
      expect(page).not.toMatch(pattern);
    }
  });

  it("renders byte-identically across two passes (deterministic)", () => {
    const a = renderToString(renderFolderIndex(dryRunIndex(), { name: "dry-run-sample" }));
    const b = renderToString(renderFolderIndex(dryRunIndex(), { name: "dry-run-sample" }));
    expect(a).toBe(b);
  });

  it("renders NO dry-run block for an ordinary folder (unchanged behavior)", () => {
    const index = buildFolderIndex(loadFolder(join(FIXTURES, "folder-sample")), OPTS);
    const page = renderToString(renderFolderIndex(index, { name: "folder-sample" }));
    expect(page).not.toContain("Dry-run result");
    expect(page).not.toContain("sm-dryrun");
  });

  it("escapes hostile bundle content instead of injecting it", () => {
    const hostile = buildFolderIndex(
      [
        {
          name: "operator-bundle.json",
          type: "json",
          text: JSON.stringify({
            schemaVersion: DRY_RUN_BUNDLE_SCHEMA,
            operatorVerdict: "<script>alert(1)</script>",
            whatHappened: "<img src=x onerror=alert(1)>",
            chainBlockingCodes: ["<b>bold-code</b>"],
            artifacts: [{ role: "<i>role</i>", present: true, valid: true }],
            files: [],
          }),
        },
      ],
      OPTS,
    );
    const page = renderToString(renderFolderIndex(hostile, { name: "hostile" }));
    expect(page).not.toContain("<script>alert(1)");
    expect(page).not.toContain("<img src=x");
    expect(page).not.toContain("<b>bold-code</b>");
    expect(page).not.toContain("<i>role</i>");
    expect(page).toContain("&lt;script&gt;");
  });
});
