/**
 * Sprint aux — typed views for the S25–S87 sniper / Phase 6 simulation schemas.
 *
 * The fixtures under ../fixtures/sample-{simulation,sniper,phase6}-*.json are
 * FICTIONAL artifacts generated by the BACKEND PRODUCTION BUILDERS (the same
 * fictional fixture chain the repo's e2e tests use — fictional mints, sample
 * labels, nothing live, no real market data, no real wallet anywhere).
 *
 * Proves, against those real shapes:
 *   - the registry recognizes every S25–S87 schema with its real CLI command;
 *   - typed views render honest state: route resolution UNAVAILABLE is the
 *     truthful capability boundary (not success, not failure), readiness shows
 *     the eleven-area evidence bar incl. route-resolution-tests, audit/handoff
 *     show the S87 route-resolution role;
 *   - SAMPLE labels stay visible; safety locks are echoed; an unsafe lock
 *     claim gets a loud tamper warning;
 *   - unknown schemas still degrade honestly (no typed view, no fake verdict);
 *   - hostile/missing-field shapes never throw and never inject;
 *   - no fake live/execution wording anywhere.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { renderToString } from "../src/lib/html.js";
import { normalizeArtifact } from "../src/lib/local-artifact.js";
import { knownSchema, isKnownSchema } from "../src/lib/report-types.js";
import { extractVerdict } from "../src/lib/folder-index.js";
import { hasTypedView, renderTypedArtifactView } from "../src/components/artifact-views.js";

function loadFixture(name: string): unknown {
  const path = fileURLToPath(new URL(`../fixtures/${name}`, import.meta.url));
  return JSON.parse(readFileSync(path, "utf8")) as unknown;
}

function typed(raw: unknown): string {
  const view = renderTypedArtifactView(normalizeArtifact(raw), raw);
  expect(view).not.toBeNull();
  return renderToString(view!);
}

/** Live/execution claims no paper/simulation view may ever make. */
const FORBIDDEN_PHRASES = [
  "trade executed",
  "trade placed",
  "transaction sent",
  "transaction signed",
  "order filled",
  "position opened",
  "ready for live",
  "live-ready",
  "live trading ready: yes",
  "safe with real funds",
  "guaranteed",
  "profitable",
];

const FIXTURES: ReadonlyArray<readonly [string, string]> = [
  ["sample-sniper-decision-v2.json", "sniper.paper.decision.report.v2"],
  ["sample-sniper-run-report-v2.json", "sniper.run.report.v2"],
  ["sample-sniper-run-report-diff-v2.json", "sniper.run.report.diff.v2"],
  ["sample-simulation-intent-plan.json", "simulation.intent.plan.v2"],
  ["sample-simulation-result.json", "simulation.result.v1"],
  ["sample-simulation-route-resolution.json", "simulation.route.resolution.v1"],
  ["sample-simulation-plan-diff.json", "simulation.intent.plan.diff.v2"],
  ["sample-simulation-result-diff.json", "simulation.result.diff.v1"],
  ["sample-phase6-audit-report.json", "phase6.audit.report.v1"],
  ["sample-phase6-readiness-report.json", "phase6.simulation.readiness.report.v1"],
  ["sample-phase6-handoff-pack.json", "phase6.simulation.handoff.pack.v1"],
];

describe("registry — every S25–S87 schema is catalogued with its real CLI", () => {
  const EXPECTED_CLI: Readonly<Record<string, string>> = {
    "sniper.paper.decision.report.v2": "paper:sniper:decide",
    "sniper.run.report.v2": "paper:sniper:report",
    "sniper.run.report.diff.v2": "paper:sniper:diff:report",
    "simulation.intent.plan.v2": "paper:simulation:intent:plan",
    "simulation.result.v1": "paper:simulation:result",
    "simulation.route.resolution.v1": "paper:simulation:route",
    "simulation.intent.plan.diff.v2": "paper:simulation:diff:plan",
    "simulation.result.diff.v1": "paper:simulation:diff:result",
    "phase6.audit.report.v1": "paper:simulation:audit",
    "phase6.simulation.readiness.report.v1": "paper:simulation:readiness",
    "phase6.simulation.handoff.pack.v1": "paper:simulation:handoff",
  };

  for (const [id, cli] of Object.entries(EXPECTED_CLI)) {
    it(`recognizes ${id} (stable, CLI ${cli}, typed view shipped)`, () => {
      const info = knownSchema(id);
      expect(info).toBeDefined();
      expect(info?.stability).toBe("stable");
      expect(info?.cli).toBe(cli);
      expect(hasTypedView(id)).toBe(true);
    });
  }

  it("every fixture declares the schema this suite expects (no drift)", () => {
    for (const [file, schema] of FIXTURES) {
      const raw = loadFixture(file) as Record<string, unknown>;
      expect(raw.schemaVersion, file).toBe(schema);
    }
  });

  it("an unknown schema is still unknown (no over-claiming)", () => {
    expect(isKnownSchema("simulation.route.resolution.v9")).toBe(false);
    expect(hasTypedView("simulation.route.resolution.v9")).toBe(false);
  });
});

describe("route resolution — UNAVAILABLE renders as the truthful boundary", () => {
  const out = typed(loadFixture("sample-simulation-route-resolution.json"));

  it("renders UNAVAILABLE as a capability boundary, never as success or failure", () => {
    expect(out).toContain("Route resolution UNAVAILABLE — the truthful capability boundary, not a failure");
    expect(out).toContain("No route resolver exists inside the simulation boundary");
    expect(out).toContain("UNAVAILABLE");
  });

  it("shows the fixed no-resolver id and that no attempt was claimed", () => {
    expect(out).toContain("unavailable-no-route-resolver");
    expect(out).toContain("the no-resolver id can never claim an attempt");
  });

  it("renders per-entry route/destination/fee facts as UNRESOLVED (never invented)", () => {
    expect(out).toContain("UNRESOLVED (never invented)");
  });

  it("echoes the safety locks including the always-false phase7LiveTradingReady", () => {
    expect(out).toContain("phase7LiveTradingReady");
    expect(out).toContain("can never claim live-trading readiness");
  });

  it("carries the artifact's own next safe action", () => {
    expect(out).toContain("Next safe action (from the artifact)");
  });
});

describe("readiness — the eleven-area evidence bar is visible", () => {
  const out = typed(loadFixture("sample-phase6-readiness-report.json"));

  it("shows the route-resolution-tests evidence area (the S86 eleventh area)", () => {
    expect(out).toContain("route-resolution-tests");
    expect(out).toContain("eleven-area evidence bar");
  });

  it("pins Phase 7 to a permanent NO in plain language", () => {
    expect(out).toContain("phase 7 live trading ready");
    expect(out).toContain("permanently; Phase 7 remains not started and unauthorized");
  });

  it("says evidence references are declarations, never verified here", () => {
    expect(out).toContain("verbatim; never verified here");
  });
});

describe("audit / handoff — the S87 route-resolution role is visible", () => {
  const audit = typed(loadFixture("sample-phase6-audit-report.json"));
  const handoff = typed(loadFixture("sample-phase6-handoff-pack.json"));

  it("the audit lists the route-resolution role among the audited roles", () => {
    expect(audit).toContain("route-resolution");
    expect(audit).toContain("including the route-resolution role added by Sprint 87");
    expect(audit).toContain("simulation.route.resolution.v1");
  });

  it("the audit leads with its verdict and never authorizes", () => {
    expect(audit).toContain("reports the chain — never authorizes anything");
    expect(audit).toContain("PASSED (no blocking finding)");
  });

  it("the handoff lists the route-resolution role with its verbatim summary", () => {
    expect(handoff).toContain("route-resolution");
    expect(handoff).toContain("including the route-resolution role added by Sprint 87");
    expect(handoff).toContain("resolutionStatus=unavailable");
  });

  it("the handoff carries the verbatim readiness verdict, never as live readiness", () => {
    expect(handoff).toContain("phase 6 SIMULATION ready (never live readiness)");
  });
});

describe("sample labels and self-declared posture stay visible", () => {
  it("the sample-fictional labels render in the plan / route / handoff views", () => {
    expect(typed(loadFixture("sample-simulation-intent-plan.json"))).toContain("sample-fictional-plan");
    expect(typed(loadFixture("sample-simulation-route-resolution.json"))).toContain("sample-fictional-route");
    expect(typed(loadFixture("sample-phase6-handoff-pack.json"))).toContain("sample-fictional-handoff");
  });

  it("every fixture view echoes the artifact's own paperOnly/simulated banner line", () => {
    for (const [file] of FIXTURES) {
      const out = typed(loadFixture(file));
      expect(out, file).toContain("self-declared — paperOnly: yes");
    }
  });
});

describe("honest degradation — tamper warnings, missing fields, hostile shapes", () => {
  it("a flipped safety lock gets a loud tamper warning", () => {
    const raw = loadFixture("sample-simulation-route-resolution.json") as Record<string, unknown>;
    const out = typed({ ...raw, neverSends: false });
    expect(out).toContain("Unsafe lock claim — treat this artifact as tampered");
    expect(out).toContain("neverSends");
  });

  it("a flipped phase7LiveTradingReady gets the same tamper warning", () => {
    const raw = loadFixture("sample-phase6-readiness-report.json") as Record<string, unknown>;
    const out = typed({ ...raw, phase7LiveTradingReady: true });
    expect(out).toContain("Unsafe lock claim — treat this artifact as tampered");
    expect(out).toContain("phase7LiveTradingReady");
  });

  it("minimal shapes (schemaVersion only) never throw and show a partial-view notice", () => {
    for (const [, schema] of FIXTURES) {
      const view = renderTypedArtifactView(
        normalizeArtifact({ schemaVersion: schema }),
        { schemaVersion: schema },
      );
      expect(view, schema).not.toBeNull();
      const out = renderToString(view!);
      expect(out, schema).toContain("Partial view");
    }
  });

  it("hostile type-mismatched shapes never throw", () => {
    for (const [, schema] of FIXTURES) {
      const hostile = {
        schemaVersion: schema,
        entries: "nope",
        artifacts: 42,
        evidence: { not: "an array" },
        base: "x",
        next: [],
        sourcePlanRef: 7,
        reasonCodeCounts: "no",
      };
      expect(() => typed(hostile), schema).not.toThrow();
    }
  });

  it("hostile string content is escaped, never injected", () => {
    const out = typed({
      schemaVersion: "simulation.intent.plan.v2",
      planLabel: "<script>alert(1)</script>",
      blocked: false,
      entryCount: 0,
    });
    expect(out).not.toContain("<script>alert");
    expect(out).toContain("&lt;script&gt;");
  });
});

describe("no fake live/execution wording in any rendered view", () => {
  for (const [file] of FIXTURES) {
    it(`${file} renders without forbidden live/execution claims`, () => {
      const lower = typed(loadFixture(file)).toLowerCase();
      for (const phrase of FORBIDDEN_PHRASES) {
        expect(lower, `"${phrase}" must never appear in ${file}`).not.toContain(phrase);
      }
    });
  }
});

describe("folder verdicts — the new diff schemas report their OWN flags only", () => {
  it("the plan diff reports change + regression from hasChange / hasNewBlocking", () => {
    const raw = loadFixture("sample-simulation-plan-diff.json");
    const verdict = extractVerdict("simulation.intent.plan.diff.v2", raw);
    // The sample diff compares a clean plan against a stop-tripped one.
    expect(verdict.hasChange).toBe("yes");
    expect(verdict.hasRegression).toBe("yes");
    expect(verdict.notes.join(" ")).toContain("hasNewBlocking");
  });

  it("the identical result self-diff reports no change and no regression", () => {
    const raw = loadFixture("sample-simulation-result-diff.json");
    const verdict = extractVerdict("simulation.result.diff.v1", raw);
    expect(verdict.hasChange).toBe("no");
    expect(verdict.hasRegression).toBe("no");
  });

  it("the run report diff v2 reads hasAnyChange / hasNewOperatorBlocking", () => {
    const raw = loadFixture("sample-sniper-run-report-diff-v2.json");
    const verdict = extractVerdict("sniper.run.report.diff.v2", raw);
    expect(verdict.hasChange).toBe("yes");
    expect(verdict.hasRegression).toBe("yes");
    expect(verdict.notes.join(" ")).toContain("hasAnyChange");
    expect(verdict.notes.join(" ")).toContain("hasNewOperatorBlocking");
  });

  it("non-diff Phase 6 artifacts carry no verdict (not-applicable, never inferred)", () => {
    for (const schema of [
      "simulation.intent.plan.v2",
      "simulation.result.v1",
      "simulation.route.resolution.v1",
      "phase6.audit.report.v1",
      "phase6.simulation.readiness.report.v1",
      "phase6.simulation.handoff.pack.v1",
    ]) {
      const verdict = extractVerdict(schema, { hasChange: true, hasRegression: true });
      expect(verdict.hasChange, schema).toBe("not-applicable");
      expect(verdict.hasRegression, schema).toBe("not-applicable");
    }
  });

  it("an unknown simulation-looking schema still gets no verdict (no fake precision)", () => {
    const verdict = extractVerdict("simulation.route.resolution.v9", { hasChange: true });
    expect(verdict.hasChange).toBe("not-applicable");
    expect(verdict.hasRegression).toBe("not-applicable");
  });
});
