/**
 * Artifact inspector page.
 *
 * Two render entry points share the same chrome:
 *   - `renderArtifact()` is the committed, static EMPTY-STATE page generated by
 *     `pnpm web:build` (registered in the page registry). It explains how to
 *     generate a loaded view and asserts the local-only/no-network posture.
 *   - `renderArtifactReport(view, source)` renders a LOADED artifact and is used
 *     by the Node-only `pnpm web:inspect` command (see ../inspect.ts) to
 *     overwrite this page with a real local report.
 *
 * Neither path loads, fetches, uploads, or executes anything. The empty-state
 * page is pure static content; the loaded page renders an already-normalized,
 * already-escaped summary.
 */

import { html, type RawHtml } from "../lib/html.js";
import { navItem } from "../lib/nav.js";
import { WEB_COMMANDS, type WebCommandRef } from "../lib/command-reference.js";
import type { NormalizedArtifact } from "../lib/local-artifact.js";
import { PageHeader } from "../components/layout.js";
import { EmptyState, RiskNotice, Section } from "../components/ui.js";
import { ICONS } from "../lib/nav.js";
import { ArtifactReportView } from "../components/artifact.js";

/** Where the loaded artifact came from (basename only — never a full path). */
export interface ArtifactSource {
  readonly name: string;
}

function header(): RawHtml {
  const nav = navItem("artifact");
  return PageHeader({ eyebrow: nav.group, title: "Artifact inspector", description: nav.description });
}

function localOnlyNotice(): RawHtml {
  return RiskNotice({
    tone: "info",
    title: "Local-only, read-only inspector.",
    body: html`This page renders <strong>one local PAPER report JSON</strong> that you generate on your own
      machine. There is <strong>no upload, no server, no network</strong>, and no wallet, keys, signing, or
      sending anywhere in this tool. Untrusted report content is escaped and capped — it is displayed, never
      executed.`,
  });
}

function CommandRow(command: WebCommandRef): RawHtml {
  return html`<article class="sm-cmd">
    <code class="sm-cmd__code">${command.command}</code>
    <p class="sm-cmd__summary">${command.summary}</p>
  </article>`;
}

function howToSection(): RawHtml {
  return Section({
    title: "How to generate this page",
    description: "Run the Node-only inspector from the repo root against one local report JSON file.",
    body: html`<div class="sm-cmdgrid">
      ${WEB_COMMANDS.map((command) => CommandRow(command))}
    </div>`,
  });
}

function rulesSection(): RawHtml {
  return Section({
    title: "What the inspector accepts",
    description: "Conservative, fail-closed input handling.",
    body: html`<ul class="sm-bullets sm-bullets--allow">
      <li>Exactly one local <code>.json</code> file passed via <code>--input</code>.</li>
      <li>Recognized PAPER report schemas are badged; unknown schemas are labelled honestly, not faked.</li>
      <li>Large or deeply-nested data is capped and summarized — the full file is never dumped inline.</li>
      <li>Directories, non-<code>.json</code> inputs, and malformed JSON are refused with a non-zero exit.</li>
      <li>
        See the <a href="research-reports.html">report viewer</a> for the full catalogue of recognized
        schemas.
      </li>
    </ul>`,
  });
}

/** Static empty-state page (committed; regenerated by `pnpm web:build`). */
export function renderArtifact(): RawHtml {
  return html`
    ${header()}
    ${localOnlyNotice()}
    ${howToSection()}
    ${rulesSection()}

    ${Section({
      title: "Loaded artifact",
      description: "Where a real local report renders once you run the inspect command.",
      body: EmptyState({
        icon: ICONS.search,
        title: "No artifact loaded",
        message:
          "This is the committed empty-state page. Run the inspect command above with --force to render a local PAPER report here. Run `pnpm web:build` to restore this empty state.",
      }),
    })}
  `;
}

/** Loaded view used by `pnpm web:inspect` to render a real local artifact. */
export function renderArtifactReport(view: NormalizedArtifact, source: ArtifactSource): RawHtml {
  return html`
    ${header()}
    ${localOnlyNotice()}

    ${Section({
      title: "Loaded artifact",
      description: "Rendered from a local file you inspected. Nothing was uploaded or sent.",
      aside: html`<code class="sm-codechip">${source.name}</code>`,
      body: ArtifactReportView(view),
    })}

    ${Section({
      title: "Reset / regenerate",
      body: html`<ul class="sm-bullets sm-bullets--plain">
        <li>Run <code>pnpm web:build</code> to restore the committed empty-state inspector page.</li>
        <li>Re-run the inspect command with a different <code>--input</code> to view another report.</li>
      </ul>`,
    })}
  `;
}
