/**
 * Local artifact FOLDER index page.
 *
 * Two render entry points share the same chrome:
 *   - `renderFolder()` is the committed, static EMPTY-STATE page generated by
 *     `pnpm web:build` (registered in the page registry). It explains the folder
 *     index, how to generate it, the verdict legend, and the local-only posture.
 *   - `renderFolderIndex(index, source)` renders a LOADED folder index and is
 *     used by the Node-only `pnpm web:inspect --dir <folder>` command (see
 *     ../inspect.ts) to overwrite this page with a real local scan.
 *
 * Neither path loads, fetches, uploads, or executes anything. The empty-state
 * page is pure static content; the loaded page renders an already-normalized,
 * already-escaped, already-bounded summary plus per-artifact sections that reuse
 * the single-artifact inspector view.
 */

import { html, type HtmlValue, type RawHtml } from "../lib/html.js";
import { navItem, ICONS } from "../lib/nav.js";
import {
  buildFolderFilterSections,
  type FolderArtifactEntry,
  type FolderFilterSection,
  type FolderIndex,
  type VerdictState,
} from "../lib/folder-index.js";
import { truncateText } from "../lib/json-access.js";
import {
  buildDryRunOverview,
  routeStatusExplanation,
  type DryRunOverview,
  type DryRunRoleStatus,
} from "../lib/dry-run-overview.js";
import { PageHeader } from "../components/layout.js";
import { EmptyState, Pill, RiskNotice, Section, StatusCard, type Tone } from "../components/ui.js";
import { DataTable, type TableColumn } from "../components/tables.js";
import { ReportSchemaBadge } from "../components/reports.js";
import { ArtifactReportView } from "../components/artifact.js";

const DASH = "—";

/** Max characters of a filename shown in a cell/title; the anchor stays unique regardless. */
const NAME_DISPLAY_MAX = 96;

/** Cap an overly long filename for display only (escaping happens at render time). */
function displayName(name: string): string {
  return truncateText(name, NAME_DISPLAY_MAX);
}

/** Where the loaded folder came from (basename only — never a full path). */
export interface FolderSource {
  readonly name: string;
}

/** Local-only dashboard commands that generate / restore this page. */
const FOLDER_COMMANDS: readonly { readonly command: string; readonly summary: string }[] = [
  {
    command:
      "pnpm web:inspect --dir <folder> --out apps/web/public/research-folder.html --force",
    summary:
      "Scan a local folder of PAPER report JSON artifacts and render this index. Local-only, no upload, no network; --force overwrites the committed empty-state page.",
  },
  {
    command: "pnpm web:inspect --dir <folder> --json",
    summary:
      "Print a machine-readable summary of the folder (counts, by-schema, per-artifact verdicts) to stdout and write no HTML file.",
  },
  {
    command: "pnpm web:build",
    summary: "Restore the committed empty-state folder index page.",
  },
];

function header(): RawHtml {
  const nav = navItem("folder");
  return PageHeader({ eyebrow: nav.group, title: "Local artifact index", description: nav.description });
}

function localOnlyNotice(): RawHtml {
  return RiskNotice({
    tone: "info",
    title: "Local-only, read-only folder index.",
    body: html`This page summarizes a <strong>local folder of PAPER report JSON</strong> that you generate on
      your own machine. There is <strong>no upload, no server, no network</strong>, and no wallet, keys,
      signing, or sending anywhere in this tool. Untrusted report content is escaped and capped — it is
      displayed, never executed.`,
  });
}

/* ------------------------------------------------------------------ *
 * Verdict presentation.
 * ------------------------------------------------------------------ */

/** A verdict badge: regression "yes" reads as a problem; change "yes" as info. */
function verdictBadge(state: VerdictState, kind: "regression" | "change"): RawHtml {
  switch (state) {
    case "yes":
      return kind === "regression"
        ? html`<span class="sm-verdict sm-verdict--regression">yes</span>`
        : html`<span class="sm-verdict sm-verdict--changed">yes</span>`;
    case "no":
      return html`<span class="sm-verdict sm-verdict--clean">no</span>`;
    case "missing":
      return html`<span class="sm-verdict sm-verdict--missing" title="Expected field absent or wrong type — not treated as false">missing</span>`;
    case "not-applicable":
      return html`<span class="sm-verdict sm-verdict--na" title="This schema carries no such verdict field">n/a</span>`;
  }
}

const VERDICT_LEGEND: readonly { readonly state: VerdictState; readonly meaning: string }[] = [
  { state: "yes", meaning: "The artifact's own flag is true." },
  { state: "no", meaning: "The artifact's own flag is false." },
  { state: "missing", meaning: "The schema carries this field, but it was absent or not a boolean — never treated as false." },
  { state: "not-applicable", meaning: "The schema has no such field (non-diff artifact, or unknown/absent schema)." },
];

function verdictLegendSection(): RawHtml {
  const rows: readonly (readonly HtmlValue[])[] = VERDICT_LEGEND.map((entry) => [
    verdictBadge(entry.state, entry.state === "yes" ? "change" : "regression"),
    entry.meaning,
  ]);
  return Section({
    title: "Verdict legend",
    description:
      "Regression and change verdicts are read straight from each recognized diff artifact — never inferred from text, filenames, or invented fields.",
    body: DataTable({
      columns: [{ header: "Verdict" }, { header: "Meaning" }],
      rows,
      caption: "“missing” is never collapsed into “no”. Unknown schemas never produce a verdict.",
    }),
  });
}

/* ------------------------------------------------------------------ *
 * Empty-state page (committed; regenerated by `pnpm web:build`).
 * ------------------------------------------------------------------ */

function CommandRow(command: { readonly command: string; readonly summary: string }): RawHtml {
  return html`<article class="sm-cmd">
    <code class="sm-cmd__code">${command.command}</code>
    <p class="sm-cmd__summary">${command.summary}</p>
  </article>`;
}

function howToSection(): RawHtml {
  return Section({
    title: "How to generate this page",
    description: "Run the Node-only inspector from the repo root against a local folder of report JSON files.",
    body: html`<div class="sm-cmdgrid">${FOLDER_COMMANDS.map((command) => CommandRow(command))}</div>`,
  });
}

function whatItDoesSection(): RawHtml {
  return Section({
    title: "What the folder index summarizes",
    description: "Conservative, fail-soft scanning of one local directory (no recursion).",
    body: html`<ul class="sm-bullets sm-bullets--allow">
      <li>Reads only local <code>.json</code> files in the folder; non-<code>.json</code> files and
        subdirectories are skipped with an honest count.</li>
      <li>Malformed JSON is listed (not interpreted) instead of crashing the scan.</li>
      <li>Each artifact is labelled by schema (known / unknown / absent) using the same registry as the
        single-artifact inspector — unknown schemas are never faked.</li>
      <li>Recognized diff artifacts surface a <code>hasRegression</code> / <code>hasChange</code> verdict;
        everything else is <code>n/a</code>.</li>
      <li>Recognized artifacts link to a per-artifact section rendered with the typed inspector view.</li>
      <li>The loaded index groups the scan into <strong>pre-rendered, static</strong> filter sections —
        all / regression / changed / unknown-or-malformed / clean — with no JavaScript and no query params.</li>
      <li>A <code>paper:sniper:dry-run</code> output folder (recognized by its valid operator bundle) gets a
        landing overview first: the operator verdict, the artifact chain, route status, and the blocking
        codes — all read verbatim from the bundle, with a loud SIMULATION-ONLY banner.</li>
    </ul>`,
  });
}

/** Static empty-state page (committed; regenerated by `pnpm web:build`). */
export function renderFolder(): RawHtml {
  return html`
    ${header()}
    ${localOnlyNotice()}
    ${howToSection()}
    ${whatItDoesSection()}
    ${verdictLegendSection()}

    ${Section({
      title: "Loaded folder index",
      description: "Where a real local scan renders once you run the inspect command above.",
      body: EmptyState({
        icon: ICONS.gauge,
        title: "No folder loaded",
        message:
          "This is the committed empty-state page. Run the inspect command above with --dir and --force to render a local folder of PAPER report JSON here. Run `pnpm web:build` to restore this empty state.",
      }),
    })}
  `;
}

/* ------------------------------------------------------------------ *
 * PAPER dry-run landing overview (rendered only when the scanned folder
 * carries a valid phase6.operator.bundle.v1 — see ../lib/dry-run-overview.ts).
 * ------------------------------------------------------------------ */

/** Verdict → presentation. The best verdict stays explicitly SIMULATION ONLY. */
function verdictPresentation(verdict: string | null): { tone: Tone; note: string } {
  switch (verdict) {
    case "reviewable-paper-only":
      return { tone: "safe", note: "Best possible verdict — and still SIMULATION ONLY, never live-trading readiness." };
    case "blocked":
      return { tone: "caution", note: "The chain carries blocking conditions — listed verbatim below." };
    case "attention":
      return { tone: "caution", note: "Something needs review before trusting this bundle." };
    case "incomplete":
      return { tone: "caution", note: "One or more chain artifacts are missing or invalid." };
    default:
      return { tone: "caution", note: "Unrecognized verdict — inspect the bundle artifact directly." };
  }
}

function paperOnlyBanner(): RawHtml {
  return RiskNotice({
    tone: "caution",
    title: "PAPER dry-run output — SIMULATION ONLY. This is NOT live trading.",
    body: html`This folder was produced by <code>paper:sniper:dry-run</code>. Nothing here signed, sent,
      or authorized anything: <strong>no live order, no transaction, no wallet, no network</strong>. A
      simulated <em>paper-enter</em> is a classification, never a trade, and no verdict on this page is
      live-trading readiness. Phase 7 (live trading) remains unauthorized.`,
  });
}

/** One chain role chip: role name + file state, linking to the artifact when present. */
function chainRoleChip(role: DryRunRoleStatus): RawHtml {
  const stateTone = role.state === "valid" ? "safe" : role.state === "invalid" ? "danger" : "caution";
  const body = html`<span class="sm-chainrole__name">${role.role}</span>
    <span class="sm-pill sm-pill--${stateTone}">${role.state}</span>`;
  return role.anchor !== null
    ? html`<a class="sm-chainrole sm-chainrole--${role.state}" href="#${role.anchor}" title="${role.fileName ?? role.role}">${body}</a>`
    : html`<span class="sm-chainrole sm-chainrole--${role.state}" title="${role.fileName ?? role.role}">${body}</span>`;
}

function dryRunVerdictSection(overview: DryRunOverview): RawHtml {
  const verdict = verdictPresentation(overview.operatorVerdict);
  const blockingCount = overview.chainBlockingCodes.total;
  const cards: readonly RawHtml[] = [
    StatusCard({
      label: "Operator verdict",
      value: overview.operatorVerdict ?? "(missing)",
      tone: verdict.tone,
      note: verdict.note,
    }),
    StatusCard({
      label: "Route resolution",
      value: overview.routeResolutionStatus ?? "(missing)",
      tone: "neutral",
      note: routeStatusExplanation(overview.routeResolutionStatus),
    }),
    StatusCard({
      label: "Blocking conditions",
      value: String(blockingCount),
      tone: blockingCount > 0 ? "caution" : "safe",
      note: blockingCount > 0 ? "codes listed verbatim below" : "none recorded in the bundle",
    }),
    StatusCard({
      label: "Readiness (verbatim)",
      value:
        overview.simulationReadyPerReadiness === null ? "unknown" : String(overview.simulationReadyPerReadiness),
      tone: "neutral",
      note: "phase6 SIMULATION readiness — never live readiness",
    }),
    StatusCard({
      label: "Bundle complete",
      value: overview.complete === null ? "unknown" : String(overview.complete),
      tone: overview.complete === true ? "safe" : "caution",
      note: `${String(overview.validRoleCount)} valid / ${String(overview.invalidRoleCount)} invalid / ${String(overview.missingRoleCount)} missing`,
    }),
    StatusCard({
      label: "Blocking trail consistent",
      value: overview.blockingTrailConsistent === null ? "unknown" : String(overview.blockingTrailConsistent),
      tone: overview.blockingTrailConsistent === true ? "safe" : "danger",
      note:
        overview.blockingTrailConsistent === false
          ? "codes disagree across the chain — treat as tampered"
          : "handoff codes match the bundled chain",
    }),
  ];
  const labels = [
    overview.bundleLabel !== null ? html`run <code class="sm-codechip">${overview.bundleLabel}</code>` : null,
    overview.operatorLabel !== null ? html`operator <code class="sm-codechip">${overview.operatorLabel}</code>` : null,
  ].filter((value) => value !== null);
  return Section({
    title: "Dry-run result",
    description:
      "Read verbatim from this folder's operator bundle — nothing on this card is recomputed or inferred.",
    aside: html`<a href="#${overview.bundleAnchor}"><code>${displayName(overview.bundleName)}</code></a>`,
    body: html`
      ${labels.length > 0 ? html`<p class="sm-muted-line">${labels.map((l, i) => (i > 0 ? html` · ${l}` : l))}</p>` : null}
      <div class="sm-cardgrid">${cards}</div>
      ${overview.whatHappened !== null ? html`<p class="sm-dryrun__happened">${overview.whatHappened}</p>` : null}
    `,
  });
}

function dryRunChainSection(overview: DryRunOverview): RawHtml {
  return Section({
    title: "Artifact chain",
    description:
      "Every role the bundle records, in chain order, with its file-backed state. Click a role to jump to that artifact's rendered section.",
    body: html`<div class="sm-chain">${overview.roles.map((role) => chainRoleChip(role))}</div>
      ${
        overview.rolesHidden > 0
          ? html`<p class="sm-muted-line">${String(overview.rolesHidden)} additional role(s) not shown.</p>`
          : null
      }`,
  });
}

function dryRunBlockingSection(overview: DryRunOverview): RawHtml {
  const codes = overview.chainBlockingCodes;
  const why = overview.whyBlocked;
  return Section({
    title: "Blocking conditions",
    description: "Chain blocking codes carried verbatim by the bundle, with the bundle's own explanations.",
    body:
      codes.items.length === 0 && why.items.length === 0
        ? html`<p class="sm-muted-line">None — the bundled chain carries no blocking condition.</p>`
        : html`
            ${codes.items.length > 0
              ? html`<ul class="sm-bullets sm-bullets--deny">
                  ${codes.items.map((code) => html`<li><code>${code}</code></li>`)}
                </ul>`
              : null}
            ${codes.hidden > 0 ? html`<p class="sm-muted-line">${String(codes.hidden)} more code(s) not shown.</p>` : null}
            ${why.items.length > 0
              ? html`<ul class="sm-bullets sm-bullets--plain">
                  ${why.items.map((line) => html`<li>${line}</li>`)}
                </ul>`
              : null}
          `,
  });
}

function dryRunNextSection(overview: DryRunOverview): RawHtml | null {
  if (overview.whatToInspectNext.items.length === 0 && !overview.hasRunSummary) return null;
  return Section({
    title: "What to inspect next",
    description: "The bundle's own next steps, carried verbatim.",
    body: html`
      ${overview.whatToInspectNext.items.length > 0
        ? html`<ul class="sm-bullets sm-bullets--plain">
            ${overview.whatToInspectNext.items.map((line) => html`<li>${line}</li>`)}
          </ul>`
        : null}
      ${overview.hasRunSummary
        ? html`<p class="sm-muted-line">
            This folder also carries <code>RUN_SUMMARY.md</code> — the run's human-readable summary (open it in
            your editor; markdown is not rendered here).
          </p>`
        : null}
    `,
  });
}

/** The full landing block for a recognized dry-run folder (or nothing). */
function dryRunOverviewBlock(index: FolderIndex): RawHtml | null {
  const overview = buildDryRunOverview(index);
  if (overview === null) return null;
  return html`<div class="sm-dryrun">
    ${paperOnlyBanner()}
    ${dryRunVerdictSection(overview)}
    ${dryRunChainSection(overview)}
    ${dryRunBlockingSection(overview)}
    ${dryRunNextSection(overview)}
  </div>`;
}

/* ------------------------------------------------------------------ *
 * Loaded page (written by `pnpm web:inspect --dir`).
 * ------------------------------------------------------------------ */

function summarySection(index: FolderIndex): RawHtml {
  const c = index.counts;
  const cards: readonly RawHtml[] = [
    StatusCard({ label: "Files scanned", value: String(c.filesScanned), tone: "neutral", note: `${c.jsonFiles} .json` }),
    StatusCard({ label: "Valid artifacts", value: String(c.validArtifacts), tone: c.validArtifacts > 0 ? "safe" : "neutral" }),
    StatusCard({
      label: "Malformed JSON",
      value: String(c.malformedFiles),
      tone: c.malformedFiles > 0 ? "caution" : "neutral",
      note: "not interpreted",
    }),
    StatusCard({ label: "Skipped (non-JSON)", value: String(c.skippedFiles), tone: "neutral" }),
    StatusCard({
      label: "Unknown schemas",
      value: String(c.unknownSchemas),
      tone: c.unknownSchemas > 0 ? "caution" : "neutral",
      note: "not faked",
    }),
    StatusCard({
      label: "With regression",
      value: String(c.withRegression),
      tone: c.withRegression > 0 ? "danger" : "safe",
      note: "hasRegression: yes",
    }),
    StatusCard({
      label: "With change",
      value: String(c.withChange),
      tone: "neutral",
      note: "hasChange: yes",
    }),
  ];
  return Section({
    title: "Scan summary",
    description: "Honest counts across the folder. Malformed and unknown artifacts are never counted as clean.",
    body: html`<div class="sm-cardgrid">${cards}</div>`,
  });
}

/** A schema badge cell that also handles the "(no schemaVersion)" group key. */
function schemaCountCell(key: string): HtmlValue {
  if (key === "(no schemaVersion)") {
    return html`<span class="sm-schema sm-schema--unknown" title="No schemaVersion field present">
      no <code>schemaVersion</code>
    </span>`;
  }
  return ReportSchemaBadge(key);
}

function schemaCountsSection(index: FolderIndex): RawHtml {
  const rows: readonly (readonly HtmlValue[])[] = index.schemaCounts.map((entry) => [
    schemaCountCell(entry.key),
    entry.status,
    String(entry.count),
  ]);
  return Section({
    title: "By schema",
    description: "Recognized vs. unknown vs. absent schemas across the valid artifacts.",
    body: DataTable({
      columns: [{ header: "Schema" }, { header: "Status" }, { header: "Count", align: "right" }],
      rows,
      emptyMessage: "No valid artifacts to group.",
    }),
  });
}

/** A schema cell for one artifact row in the artifact list. */
function artifactSchemaCell(entry: FolderArtifactEntry): HtmlValue {
  if (entry.status === "malformed") return DASH;
  if (entry.schemaVersion === null) {
    return html`<span class="sm-schema sm-schema--unknown" title="No schemaVersion field present">
      no <code>schemaVersion</code>
    </span>`;
  }
  return ReportSchemaBadge(entry.schemaVersion);
}

/** Columns shared by every artifact-list table (the "all" list and each filter group). */
const ARTIFACT_COLUMNS: readonly TableColumn[] = [
  { header: "Artifact" },
  { header: "Schema" },
  { header: "Status" },
  { header: "Typed view" },
  { header: "Regression" },
  { header: "Change" },
];

/** One artifact row, shared by the full list and the filtered groups. */
function artifactRow(entry: FolderArtifactEntry): readonly HtmlValue[] {
  return [
    html`<a href="#${entry.anchor}"><code>${displayName(entry.name)}</code></a>`,
    artifactSchemaCell(entry),
    entry.status === "malformed" ? Pill("malformed JSON", "danger") : Pill("valid JSON", "safe"),
    entry.status === "valid" ? (entry.hasTypedView ? Pill("typed view", "safe") : Pill("generic", "muted")) : DASH,
    verdictBadge(entry.verdict.hasRegression, "regression"),
    verdictBadge(entry.verdict.hasChange, "change"),
  ];
}

/** A summary card linking to one filter section's anchor (no JS, just a fragment link). */
function filterCard(section: FolderFilterSection): RawHtml {
  return html`<a class="sm-filtercard sm-filtercard--${section.category}" href="#${section.anchor}">
    <span class="sm-filtercard__count">${String(section.artifacts.length)}</span>
    <span class="sm-filtercard__label">${section.title}</span>
  </a>`;
}

/** One pre-rendered filter group: a counted header plus its (subset) table. */
function filterSection(section: FolderFilterSection): RawHtml {
  const count = section.artifacts.length;
  return html`<section class="sm-filtersection sm-filtersection--${section.category}" id="${section.anchor}">
    <div class="sm-filtersection__summary">
      <h3 class="sm-filtersection__title">
        ${section.title}
        <span class="sm-filtersection__count">${String(count)}</span>
      </h3>
      <p class="sm-filtersection__desc">${section.description}</p>
    </div>
    ${
      count === 0
        ? html`<p class="sm-muted-line">No artifacts in this group.</p>`
        : DataTable({ columns: ARTIFACT_COLUMNS, rows: section.artifacts.map((entry) => artifactRow(entry)) })
    }
  </section>`;
}

/**
 * The artifact list, rendered as static, pre-filtered sections (no JavaScript).
 * The "all" group keeps the `sm-folder-artifacts` id so the per-artifact
 * "back to list" links still resolve; the four filtered groups get their own
 * deterministic anchors. Each group's header count equals the rows it renders.
 */
function artifactListSection(index: FolderIndex): RawHtml {
  const sections = buildFolderFilterSections(index);
  return Section({
    title: "Artifacts",
    description:
      "Every JSON file found, recognized or not. Click an artifact to jump to its rendered section, or use the pre-rendered filter groups below — they are static (no JavaScript, no query params).",
    body: html`<div class="sm-artifactlist sm-filtersections">
      <div class="sm-filtercards">${sections.map((section) => filterCard(section))}</div>
      ${sections.map((section) => filterSection(section))}
    </div>`,
  });
}

function skippedSection(index: FolderIndex): RawHtml {
  if (index.skipped.length === 0) {
    return Section({
      title: "Skipped files",
      body: html`<p class="sm-muted-line">No non-JSON files or subdirectories were skipped.</p>`,
    });
  }
  const rows: readonly (readonly HtmlValue[])[] = index.skipped.map((entry) => [
    html`<code>${displayName(entry.name)}</code>`,
    entry.reason,
  ]);
  return Section({
    title: "Skipped files",
    description: "Non-JSON files and subdirectories are ignored with an honest count.",
    body: DataTable({
      columns: [{ header: "Name" }, { header: "Reason" }],
      rows,
    }),
  });
}

function notesSection(index: FolderIndex): RawHtml | null {
  if (index.notes.length === 0) return null;
  return Section({
    title: "Inspector notes",
    description: "Honest summary of edge cases found while scanning.",
    body: html`<ul class="sm-bullets sm-bullets--plain">
      ${index.notes.map((note) => html`<li>${note}</li>`)}
    </ul>`,
  });
}

/** The back-to-list link shown atop each per-artifact section. */
function backToList(): RawHtml {
  return html`<a class="sm-folderindex__back" href="#sm-folder-artifacts">↑ Back to artifact list</a>`;
}

/** One per-artifact section, anchored for the artifact-list links. */
function artifactSection(entry: FolderArtifactEntry): RawHtml {
  if (entry.status === "malformed" || entry.view === null) {
    return Section({
      id: entry.anchor,
      title: displayName(entry.name),
      aside: backToList(),
      body: RiskNotice({
        tone: "caution",
        title: "Malformed JSON — not interpreted",
        body: html`This file could not be parsed as JSON, so no schema, verdict, or fields were read.
          ${entry.parseError !== null ? html`<br />Parser said: <code>${entry.parseError}</code>` : null}`,
      }),
    });
  }
  return Section({
    id: entry.anchor,
    title: displayName(entry.name),
    aside: backToList(),
    body: ArtifactReportView(entry.view, entry.raw),
  });
}

/**
 * Loaded view used by `pnpm web:inspect --dir` to render a real folder scan.
 * The per-artifact sections reuse the single-artifact inspector view, so a
 * recognized artifact gets its typed view and every artifact gets the generic,
 * capped, escaped summary.
 */
export function renderFolderIndex(index: FolderIndex, source: FolderSource): RawHtml {
  return html`
    ${header()}
    ${localOnlyNotice()}
    ${dryRunOverviewBlock(index)}

    <div class="sm-folderindex">
      ${Section({
        title: "Folder",
        description: "Scanned from a local directory you inspected. Nothing was uploaded or sent.",
        aside: html`<code class="sm-codechip">${source.name}</code>`,
        body: html`<p class="sm-muted-line">
          ${String(index.counts.validArtifacts)} valid artifact(s),
          ${String(index.counts.malformedFiles)} malformed,
          ${String(index.counts.skippedFiles)} skipped.
        </p>`,
      })}
      ${summarySection(index)}
      ${schemaCountsSection(index)}
      ${artifactListSection(index)}
      ${skippedSection(index)}
      ${notesSection(index)}
      ${verdictLegendSection()}

      ${Section({
        title: "Per-artifact views",
        description: "Each recognized artifact rendered with the typed inspector view; malformed files are clearly labelled.",
        body: index.artifacts.length === 0
          ? html`<p class="sm-muted-line">No artifacts to render.</p>`
          : html`${index.artifacts.map((entry) => artifactSection(entry))}`,
      })}

      ${Section({
        title: "Reset / regenerate",
        body: html`<ul class="sm-bullets sm-bullets--plain">
          <li>Run <code>pnpm web:build</code> to restore the committed empty-state folder index page.</li>
          <li>Re-run the inspect command with a different <code>--dir</code> to scan another folder.</li>
        </ul>`,
      })}

      <p class="sm-artifactview__note">
        Read-only, local, simulated paper artifacts. Not a live result, not advice, not a profitability claim.
      </p>
    </div>
  `;
}
